# This is a basic workflow to help you get started with Actions
name: build-calculator-images

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

defaults:
  run:
    working-directory: apps

env:
  BACKEND_APP_NAME: js-calc-backend
  FRONTEND_APP_NAME: js-calc-frontend

jobs:
  build:
    runs-on: ubuntu-latest
    name: build
    permissions:
      packages: write
      contents: read
    steps:
    - uses: actions/checkout@v2

    - name: Build images
      run: |
        cd $BACKEND_APP_NAME
        docker build . --file Dockerfile --tag $BACKEND_APP_NAME --label "runnumber=${GITHUB_RUN_ID}"
        cd ../$FRONTEND_APP_NAME
        docker build . --file Dockerfile --tag $FRONTEND_APP_NAME --label "runnumber=${GITHUB_RUN_ID}"

    - name: Log in to registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Push images
      run: |
        BACKEND_IMAGE_ID=ghcr.io/${{ github.repository_owner }}/container-apps/$BACKEND_APP_NAME
        docker tag $BACKEND_APP_NAME $BACKEND_IMAGE_ID:${GITHUB_RUN_ID}
        docker tag $BACKEND_APP_NAME $BACKEND_IMAGE_ID:latest
        docker push $BACKEND_IMAGE_ID:${GITHUB_RUN_ID}
        docker push $BACKEND_IMAGE_ID:latest

        FRONTEND_IMAGE_ID=ghcr.io/${{ github.repository_owner }}/container-apps/$FRONTEND_APP_NAME
        docker tag $FRONTEND_APP_NAME $FRONTEND_IMAGE_ID:${GITHUB_RUN_ID}
        docker tag $FRONTEND_APP_NAME $FRONTEND_IMAGE_ID:latest
        docker push $FRONTEND_IMAGE_ID:${GITHUB_RUN_ID}
        docker push $FRONTEND_IMAGE_ID:latest
